targets:
  dns:
    - 2400:3200:baba::1
    - 8.8.8.8
    - 1.1.1.1
    - 223.5.5.5
  china:
    - baidu.com
    - zhihu.com
  local:
    - 192.168.2.1
  world:
    - cloudflare.com
    - google.com
    - github.com
    - youtube.com
    - region1.v2.argotunnel.com
